artifactsRoot: artifacts

dataIngestion:
    rootDir: artifacts/data_ingestion
    sourceURL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
    localDataFile: artifacts/data_ingestion/data.zip
    unzipDir: artifacts/data_ingestion

dataTransformation:
    rootDir: artifacts/data_transformation
    dataPath: artifacts/data_ingestion/samsum_dataset
    tokenizerName: google/pegasus-cnn_dailymail

modelTrainer:
    rootDir: artifacts/model_trainer
    dataPath: artifacts/data_transformation/samsum_dataset
    modelCkpt: google/pegasus-cnn_dailymail